### ISSUE TITLE
add python submit/wait example?

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-workflow-examples#45]
Per discussion yesterday, it might be useful to look through the toy python programs in flux-core's `t/job-manager` directory that demonstrate the python job submit and wait interfaces, and see if a new example could be put together?  These examples also use the new `JobspecV1()` class to build jobspec.

Asynchronously submit jobs and then wait for them to complete in any order:
https://github.com/flux-framework/flux-core/blob/master/t/job-manager/submit-waitany.py

Same, but keeping at most some number of jobs active:
https://github.com/flux-framework/flux-core/blob/master/t/job-manager/submit-sliding-window.py

Wait for specific jobs, blocking until each completes:
https://github.com/flux-framework/flux-core/blob/master/t/job-manager/submit-wait.py

What's kind of nice about `job.wait()` is one doesn't need to use an event loop/reactor to manage the concurrency.  Also the semantics are similar to the [wait(2)](http://man7.org/linux/man-pages/man2/wait.2.html) system call, which is familiar to many.

**Comment by grondo** [comment]
I agree, that would be a great example!

However, be sure to mention this interface is only for instance owners.

**Comment by cmoussa1** [comment]
I like this too; I will start working on implementing these into their own example! I'm thinking I could include all three parts into one example since they are closely related, like a **part(a)**, **part(b)**, and **part(c)**, similar to how [example2](https://github.com/flux-framework/flux-workflow-examples/tree/master/example2) is structured. 

Do you think we could reuse one the `compute.py` scripts from **example2** for the example job being submitted? Or did you have something else in mind?

**Comment by cmoussa1** [comment]
This issue can be closed now that PR #50 is merged! 🎉
